version: '3.8'
services:

  quietspace-monolith-db:
    container_name: ${DB_HOST_NAME}
    image: mysql:8.0
    restart: on-failure
    volumes:
      - quietspace_monolith_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_USERNAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    networks:
      - monolith-network
    ports:
      - ${EXP_DB_PORT_NUMBER}:${DB_PORT_NUMBER}

  quietspace-monolith:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    image: thural/quietspace:monolith
    container_name: ${SERVER_HOST_NAME}
    depends_on:
      - quietspace-monolith-db
    env_file:
      - .env
    networks:
      - monolith-network
    ports:
      - ${SERVER_PORT_NUMBER}:${SERVER_PORT_NUMBER}

volumes:
  quietspace_monolith_data:

networks:
  monolith-network:
    name: monolith-network
    driver: bridge