apiVersion: v1
kind: Secret
metadata:
  name: common-secret
type: Opaque
data:
  BACKEND_DB_ROOT-USER: cm9vdA==
  BACKEND_DB_ROOT-PASSWORD: QHJvb3Q4ODg=
  BACKEND_DB_USER: dGh1cmFs
  BACKEND_DB_USER-PASSWORD: QGRvbHBoaW44ODg=
  DB_VENDOR: TVlTUUw=
  DB_ADDR: bXlzcWw=
  DB_DATABASE: a2V5Y2xvYWs=
  DB_USER: dGh1cmFs
  DB_PASSWORD: QGtleWNsb2FrODg4
  KEYCLOAK_ADMIN: YWRtaW4=
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4=
  MYSQL_ROOT_PASSWORD: QHJvb3Q4ODg=
  MYSQL_DATABASE: a2V5Y2xvYWs=
  MYSQL_USER: dGh1cmFs
  MYSQL_PASSWORD: QGtleWNsb2FrODg4