spring:
  profiles:
    default: default
    active: ${ACTIVE_PROFILE}
  mail:
    host: localhost
    port: 1025
    username: thural
    password: thural
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  application:
    name: quietspace-backend
    security:
      jwt:
        secret-key: ${SECRET_KEY}
        expiration: 86400000 # a day
        refresh-token:
          expiration: 604800000 # 7 days
    mailing:
      frontend:
        activation-url: http://localhost:5000/activate-account
    file:
      uploads:
        photos-output-path: ./uploads