spring:

  devtools:
    livereload.enabled: true
    restart:
      enabled: true

  application:
    name: quietspace-backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quietspace
    username: ${DB_USER_USERNAME}
    password: ${DB_USER_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    open-in-view: true
    show-sql: true

  flyway:
    enabled: false

logging:
  file:
    name: quietspace
  level:
    root: WARN
    org.hibernate.orm.jdbc.bind: TRACE
    dev.thural.quietspace.service: WARN
    org.hibernate.sql: DEBUG
    org.springframework.web.servlet.handler.HandlerMappingIntrospector: ERROR
  logback:
    rollingpolicy:
      max-file-size: 2MB
      max-history: 3

server:
  port: 8080
