version: '3.8'
services:

  quietspace-monolith-db:
    container_name: ${DB_HOST_NAME}
    image: mysql:8.0
    restart: on-failure
    volumes:
      - quietspace_monolith_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      #      - ./mysql:/var/lib/mysql (for in folder data storage)
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_USERNAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    networks:
      - monolith-network
    ports:
      - ${EXP_DB_PORT_NUMBER}:${DB_PORT_NUMBER}

  quietspace-monolith:
    build:
      context: ../
      dockerfile: ./docker/prod/Dockerfile
    image: thural/quietspace:monolith
    container_name: ${SERVER_HOST_NAME}
    depends_on:
      - quietspace-monolith-db
    env_file:
      - .env
    environment:
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      DB_USER_USERNAME: ${DB_USER_USERNAME}
      DB_PORT_NUMBER: ${DB_PORT_NUMBER}
      DB_NAME: ${DB_NAME}
      DB_URL: ${DB_URL}
      DB_HOST_NAME: ${DB_HOST_NAME}
      APP_VERSION: ${APP_VERSION}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
    networks:
      - monolith-network
    ports:
      - ${SERVER_PORT_NUMBER}:${SERVER_PORT_NUMBER}

  keycloak_db:
    image: postgres:16.1
    container_name: ${KEYCLOAK_DB_HOST}
    environment:
      POSTGRES_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak_db_data:/bitnami/postgresql
    ports:
      - ${KEYCLOAK_DB_PORT_EXP}:${KEYCLOAK_DB_PORT}
    networks:
      - monolith-network

  keycloak:
    image: bitnami/keycloak:24.0.2
    user: root
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: ${KEYCLOAK_DB_HOST}
      KEYCLOAK_DATABASE_NAME: ${KEYCLOAK_DB_NAME}
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_DATABASE_USER: ${KEYCLOAK_DB_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_EXTRA_ARGS: --import-realm
      KEYCLOAK_CREATE_ADMIN_USER: "true"
    ports:
      - ${KEYCLOAK_PORT}:${KEYCLOAK_PORT}
    depends_on:
      - keycloak_db
    volumes:
      - ../keycloak/theme:/opt/bitnami/keycloak/themes/
      - ../keycloak/realms/:/opt/bitnami/keycloak/data/import
    networks:
      - monolith-network

volumes:
  quietspace_monolith_data:
  keycloak_db_data:

networks:
  monolith-network:
    name: monolith-network
    driver: bridge