version: '3.8'
services:

  quietspace-monolith-db:
    container_name: ${DB_HOST_NAME}
    image: mysql:8.0
    restart: on-failure
    volumes:
      - quietspace_monolith_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      #      - ./mysql:/var/lib/mysql (for in folder data storage)
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_USERNAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    networks:
      - monolith-network
    ports:
      - ${EXP_DB_PORT_NUMBER}:${DB_PORT_NUMBER}

  quietspace-monolith:
    build:
      context: ../../
      dockerfile: ./infrastructure/docker/buildfiles/prod/Dockerfile
    image: thural/quietspace:monolith
    container_name: ${SERVER_HOST_NAME}
    depends_on:
      - quietspace-monolith-db
    env_file:
      - /.env
    environment:
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      DB_USER_USERNAME: ${DB_USER_USERNAME}
      DB_PORT_NUMBER: ${DB_PORT_NUMBER}
      DB_NAME: ${DB_NAME}
      DB_URL: ${DB_URL}
      DB_HOST_NAME: ${DB_HOST_NAME}
      APP_VERSION: ${APP_VERSION}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
    networks:
      - monolith-network
    ports:
      - ${SERVER_PORT_NUMBER}:${SERVER_PORT_NUMBER}

  keycloak-db:
    container_name: ${KEYCLOAK_DB_HOST}
    hostname: ${KEYCLOAK_DB_HOST}
    image: mysql:5.7
    restart: on-failure
    volumes:
      - keycloak_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${KEYCLOAK_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${KEYCLOAK_DB_NAME}
      MYSQL_USER: ${KEYCLOAK_DB_USER}
      MYSQL_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    networks:
      - monolith-network

  keycloak:
    container_name: ${KEYCLOAK_HOST}
    hostname: ${KEYCLOAK_HOST}
    image: quay.io/keycloak/keycloak:24.0.3
    restart: on-failure
    volumes:
      - realms-data/:/opt/keycloak/data/import/
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: ${KEYCLOAK_DB_NAME}
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    networks:
      - monolith-network
    ports:
      - ${KEYCLOAK_PORT}:8080
    depends_on:
      - keycloak-db

volumes:
  quietspace_monolith_data:
  keycloak_db_data:
  realms-data:

networks:
  monolith-network:
    name: monolith-network
    driver: bridge