version: '3.8'
services:

  quietspace-monolith-db:
    container_name: ${DB_HOST_NAME}
    image: mysql:8.0
    restart: on-failure
    volumes:
      - quietspace_monolith_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      #      - ./mysql:/var/lib/mysql (for in folder data storage)
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_USERNAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    networks:
      - monolith-network
    ports:
      - ${EXP_DB_PORT_NUMBER}:${DB_PORT_NUMBER}

  quietspace-monolith:
    build:
      context: ../..
      dockerfile: buildfiles/prod/Dockerfile
    image: thural/quietspace:monolith
    container_name: ${SERVER_HOST_NAME}
    depends_on:
      - quietspace-monolith-db
    env_file:
      - .env
    environment:
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      DB_USER_USERNAME: ${DB_USER_USERNAME}
      DB_PORT_NUMBER: ${DB_PORT_NUMBER}
      DB_NAME: ${DB_NAME}
      DB_URL: ${DB_URL}
      DB_HOST_NAME: ${DB_HOST_NAME}
      APP_VERSION: ${APP_VERSION}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
    networks:
      - monolith-network
    ports:
      - ${SERVER_PORT_NUMBER}:${SERVER_PORT_NUMBER}

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  quietspace_monolith_data:

networks:
  monolith-network:
    name: monolith-network
    driver: bridge