version: '3.8'
services:

  quietspace-monolith-db:
    container_name: ${DB_HOST_NAME}
    image: mysql:8.0
    restart: on-failure
    volumes:
      - quietspace_monolith_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_USERNAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    networks:
      - monolith-network
    ports:
      - ${EXP_DB_PORT_NUMBER}:${DB_PORT_NUMBER}

  quietspace-monolith-dev:
    build:
      context: ../..
      dockerfile: dev/Dockerfile
    image: thural/quietspace:monolith-dev
    container_name: ${SERVER_HOST_NAME}
    depends_on:
      - quietspace-monolith-db
    env_file:
      - ./.env
    networks:
      - monolith-network
    ports:
      - ${EXP_SERVER_PORT_NUMBER}:${SERVER_PORT_NUMBER}
    volumes:
      - ./:/app
      - /target

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  quietspace_monolith_data:

networks:
  monolith-network:
    name: monolith-network
    driver: bridge