apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: thural/quietspace:monolith
          ports:
            - containerPort: 8181
          env:
            - name: DB_USER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: BACKEND_DB_USER
            - name: DB_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: BACKEND_DB_USER-PASSWORD
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: mysql-url
---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
      nodePort: 32000