apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - name: keycloak-db
          image: mysql:5.7
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: common-secret
---

apiVersion: v1
kind: Service
metadata:
  name: keycloak-db-service
spec:
  selector:
    app: keycloak-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306